[project]
name = "ais-dev2il-wine-quality-full"
version = "0.1.0"
description = "This version also contains the complete guide to finish the project."
readme = "README.md"
requires-python = ">=3.13" # as in the course always, we'll use Python 3.13
dependencies = [
    "dvc>=3.67.1",
    "fastapi>=0.142.2",
    "fastparquet>=2026.9.0",
    "mlflow>=3.16.1",
    "pandas>=3.0.6",
    "pyarrow>=25.0.1",
    "scikit-learn>=1.9.1",
    "uvicorn>=0.54.0",
] # Here we'll have to add all of the dependencies later
